# Generated by Django 4.2 on 2024-10-04 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoryApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conferance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='')),
                ('desciption', models.CharField(max_length=150, verbose_name='')),
                ('start_date', models.DateField(verbose_name='')),
                ('end_date', models.DateField(verbose_name='')),
                ('location', models.CharField(max_length=50, verbose_name='')),
                ('price', models.FloatField(verbose_name='')),
                ('capacity', models.IntegerField(verbose_name='')),
                ('program', models.FileField(upload_to=None, verbose_name='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conferances', to='categoryApp.category')),
            ],
        ),
    ]
