# Generated by Django 4.2 on 2024-09-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('matricule', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='')),
                ('modele', models.CharField(max_length=20, verbose_name='')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='price')),
                ('description', models.TextField(blank=True, verbose_name='')),
            ],
        ),
    ]
